Adapt Newspeak Files
smarr/SOMns pull request #190
Opened 2017-10-11 11:18 UTC by daumayr

Adds support for file access similar to NewSpeak, the major difference in functionality is the lack of streams.

- FileDescriptor used to read/write files, a integrated buffer is used to store read data and data to write.
- FilePath: represents a single file or directory and provides some operations (e.g. copy, move, size)
- FilePattern: represents a set of files or directories in the form of a Path with wildcards (*, ?) and provides operations (e.g. pathsDo: , delete).

`
f:: FilePath for: ('/directory/file'). //create a filepath.
d:: f open: #readwrite ifFail: [:r|]. //returns file descriptor.
d buffer at: 1 put: 127.
d write: 1 at: 0 ifFail: [:r|]. //write 01111111 at the files beginning.
`

2017-10-11 11:23 UTC, smarr commented
Thanks for the PR!

Haven't looked at the code yet. So, just some basic first questions:

The file gives us access to byte buffers, or what exactly is `buffer`? An integer array?
Any way to read stuff as a string?

Are you already using it for something?
Or do you plan to use it for something specific?

2017-10-11 11:29 UTC, daumayr commented
The buffer is a SOMns Array (long), reading stuff as a string is currently not supported, for that streams would be necessary.
Currently it is used in the Tests only, when expanding replay to deal with external communication I am going to make a benchmark that uses it.

2017-10-11 15:51 UTC, smarr requested changes
There are a couple of things, I'd prefer to see changed I think:

- return values, self/this is often preferable to nil
- block dispatch nodes would be better than hardcoded invokes
- please remove dead code
- tests better integrated with unit tests
and a few other things

2017-10-11 15:51 UTC, smarr commented on tests/files/test.sh
> +#!/bin/bash
Why did you chose to run those tests separately and not as unit tests with the other things in [TestRunner](https://github.com/smarr/SOMns/blob/master/core-lib/TestSuite/TestRunner.ns#L85)?

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +    /*
Please don't commit dead code

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +    // assert fileDescriptorClass == null || cls == null;
No dead code please

2017-10-11 15:51 UTC, smarr commented on core-lib/Files.ns
> +(* This code was derived by converting the Strongtalk File classes to Newspeak, which is why the Sun Microsystems copyright and BSD license below applies.
Is this an unedited copy of the file?
If not, could you first have a commit with the original, and then the necessary changes?
Makes it much easier to track divergence.

Also, any chance you could improve the formatting of the file for human readers? (ideally in a separate commit)

2017-10-11 15:51 UTC, smarr commented on core-lib/Files.ns
> +  (*
No dead code please (also in other places)

2017-10-11 15:51 UTC, smarr commented on core-lib/Kernel.ns
> +    public ~= other = ( ^ (self = other) not )
Value defines the `<>`. Would be good if we could just use that and don't have to introduce the `~=`, which is meant for pointer objects only.

2017-10-11 15:51 UTC, smarr commented on core-lib/Kernel.ns
> +    public last = ( ^ isEmpty ifTrue: [nil] ifFalse: [storage at: (lastIdx - 1)] )
Please test this, where the other Vector things are tested

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/FilePrims.java
> +      return Nil.nilObject;
I think it is common to return the written value.

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/FilePrims.java
> +      return Nil.nilObject;
Might be nicer to return the `file`?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/FilePrims.java
> +      return Nil.nilObject;
Might be nicer to return `file`?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/FilePrims.java
> +      return Nil.nilObject;
Might be nicer to return `file`?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/FilePrims.java
> +      return Nil.nilObject;
Might be nicer to return `file`?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +      for (int i = 0; i < content.length; i++) {
Is this just `System.arraycopy(...)`?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +      if (content != null) {
shouldn't this be checked before you do `content.length` in line 33?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +        fail.getMethod().invoke(new Object[] {fail, e.toString()});
would be nicer if you'd use a block dispatch node here instead of doing it manually, and unoptimized.

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +        fail.getMethod().invoke(new Object[] {fail, e.toString()});
block dispatch node for all these block things?

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +      return Nil.nilObject;
I don't like all those nil returns, usually, self is returned implicitly in Smalltalk/Newspeak

2017-10-11 15:51 UTC, smarr commented on src/som/primitives/PathPrims.java
> +        throw new RuntimeException(e);
This isn't a good solution. Would be nicer if you throw a proper Smalltalk exception here.
NotAValue, or index out of bounds are examples, I think

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      fail.getMethod().invoke(new Object[] {fail, e.toString()});
It would be better to use a block dispatch node, which you probably need to pass in as a parameter from the AST node where you call this method.

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      if (mode.getString().equals("read")) {
Would be nicer if you just obtain the symbol for `"read"` and then compare identity

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      } else {
Also, what does Newspeak do if you pass in `#foobar`? or `nil`, or whatever for `mode`? here we get crashes, or if it is any symbol, we get write access. Might be better to have an exception or call the failure block?

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +  public void closeFile() {
Hm, you got java doc on the next method, but not here?

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      fail.getMethod().invoke(new Object[] {fail, "File not open"});
block node please, also the other cases.

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      // punish users for using this loophole
ehm, no?! Throw a proper language level exception, please.

2017-10-11 15:51 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      e.printStackTrace();
A Smalltalk exception would be much nicer

2017-10-16 07:50 UTC, daumayr commented on core-lib/Files.ns
> +(* This code was derived by converting the Strongtalk File classes to Newspeak, which is why the Sun Microsystems copyright and BSD license below applies.
The File API was split into multiple files and classes which I merged, so I don't think committing changes on top of the newspeak original would make sense. Also the formatting was worse. I am going to change that comment to say it's based on NewSpeak File classes.

2017-10-16 07:53 UTC, daumayr commented on core-lib/Files.ns
> +  (*
it's a public method accessible by users (which isn't used internally)

2017-10-16 07:58 UTC, daumayr commented on core-lib/Kernel.ns
> +    public ~= other = ( ^ (self = other) not )
ok, i didn't know about  the <> operator

2017-10-16 08:17 UTC, daumayr commented on src/som/primitives/PathPrims.java
> +      return Nil.nilObject;
the primitive doesn't have a self, or should i return the string argument?

2017-10-16 09:04 UTC, smarr commented on core-lib/Files.ns
> +  (*
`writeStream` looks like it is in a comment, so, it's not accessible?

2017-10-16 09:06 UTC, smarr commented on core-lib/Files.ns
> +(* This code was derived by converting the Strongtalk File classes to Newspeak, which is why the Sun Microsystems copyright and BSD license below applies.
Then please carefully attribute the source.
We need to be able to at least find the original files, ideally with an URL into the original repo for each, including version information.

2017-10-16 09:08 UTC, smarr commented on src/som/primitives/PathPrims.java
> +      return Nil.nilObject;
Hm, ok, for these cases `nil` might be fine. In other case, the first parameter might be more useful.

2017-10-16 11:58 UTC, daumayr commented on core-lib/Files.ns
> +  (*
I misinterpreted the comment, only the (* of the comment was visible. I decided to keep the stream based methods as comments for the case that streams are implemented in the future. Those methods could be useful for reading text from files.

2017-10-16 12:00 UTC, daumayr commented on tests/files/test.sh
> +#!/bin/bash
hm, right, i didn't end up needing batch magic for cleanup

2017-10-17 12:13 UTC, daumayr commented on core-lib/Kernel.ns
> +    public last = ( ^ isEmpty ifTrue: [nil] ifFalse: [storage at: (lastIdx - 1)] )
i am going to add a test for `first` aswell  ;)

2017-11-06 18:47 UTC, smarr commented
Ok, I did some more polishing, moving test files a bit around, fix formatting a little. Nothing much of consequence.
I squashed the changes, too, since the history didn't reflect anything useful.

@daumayr if you don't have any further things, I'll merge it.

2017-11-06 18:48 UTC, smarr commented
@richard-roberts ah, perhaps interesting for you to have a brief look. This adds file support based on Newspeak. Might be useful for Grace.

2017-11-06 18:59 UTC, daumayr commented
@smarr you can merge it, the broken tests are already broken in dev, i'll take a look at that separately.

2017-11-06 19:05 UTC, richard-roberts commented
Looks nice, thanks @daumayr. Early next year I hope to get our self-hosting Grace compiler running on SOMns, these changes will be useful for getting that going!

2017-11-06 22:23 UTC, merged