Adapted Streams Library from Newspeak
smarr/SOMns pull request #204
Opened 2017-12-17 11:14 UTC by daumayr

The Streams library of Newspeak was adapted to SOMns, it provides streams to read/write from files, collections (Vectors), and also offers character conversion. 
The stream related file methods were added to the file library, making it easier to read/write files, as it is no longer necessary to directly manipulate the buffers.

Below is an example that shows how easy an entire text file can be read:
```
fp:: FilePath for: '/home/user/aFile'.
cis:: fp charInputStream.
text:: cis next: (cis size).
cis close.
```

Similar for writing:
```
fp:: FilePath for: '/home/user/aFile'.
cos:: fp charOutputStream.
cos putAll: 'aString'.
cos close.
```

2017-12-17 11:16 UTC, daumayr commented
The contents of this PR are based on PR #201

2017-12-20 23:58 UTC, smarr requested changes
Thanks a lot for preparing this. Here the first part of review.

2017-12-20 23:58 UTC, smarr commented on core-lib/Files.ns
> +    (*stream stuff*)
Not a helpful comment, please drop...

2017-12-20 23:58 UTC, smarr commented on core-lib/Files.ns
> +    (*stream stuff*)
Not a helpful comment, please drop...

2017-12-20 23:58 UTC, smarr commented on core-lib/Files.ns
> +    charInputStream ^ <CharInputStream> = (
that's not api? that's implicitly protected? same with following methods?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public printOn: stream = (
That's debugging functionality?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public do: block = (
Why do we need #do: on strings?
Also, could you please add a test for any addition to Kernel.ns?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public from: charArray = (
What's the error when `charArray` isn't what it is supposed to be? Invalid arg exception or something alike? would be good to document.

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public asciiValue: val = (
What's this? an empty method?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public fromValue: val = (
isn't `from:` sufficient? and the `val` should perhaps be `anInt`? or document the type, please

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public value: char = (
No idea what this is supposed to do. What does it return? an integer? What kind of value? ASCII, utf-8?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +    public backspace = (^'\b')
Why are these needed?

2017-12-20 23:58 UTC, smarr commented on core-lib/Kernel.ns
> +  public class StringBuilder = Object (
Is this needed? At least remove the unnecessary whitespace:

```
public class StringBuilder = Object ()() : (
  public new: size = ( ^ vmMirror array: self new: size )
)
```

2017-12-21 13:21 UTC, smarr requested changes
Another bunch of things.
For the whole 'exception' and strictness discussion, if you prefer not to do that now, I am fine with skipping it for now, but please create an issue to document it as an open TODO.

2017-12-21 13:21 UTC, smarr commented on src/som/primitives/StringPrims.java
> +      return new String(new char[] {(char) val});
This is very forgiving, not sure we want this, might be surprising. Might need to check the val to be in range, and throw an exception otherwise?

2017-12-21 13:21 UTC, smarr commented on src/som/primitives/StringPrims.java
> +        sb.append((String) o);
This doesn't ensure that the strings are all 1-char long, right? Might need to error on invalid 'chars'?

2017-12-21 13:21 UTC, smarr commented on src/som/primitives/StringPrims.java
> +      assert c != null && c.length() == 1;
This should probably be throwing a SOMns exception instead of failing an assertion.

2017-12-21 13:21 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +      dispatchHandler.executeDispatch(new Object[] {fail, "invalid access mode"});
Should the error include the wrong value, `mode`? Would make it easier to debug.

2017-12-21 13:21 UTC, smarr commented on src/som/vmobjects/SFileDescriptor.java
> +    read("r"), write("rw"), readwrite("rw");
I think it is common to have enum members be named all caps, since they are constants.

2017-12-21 13:21 UTC, smarr commented on tests/streams/.gitignore
> +*.txt
is this needed?

2018-01-16 09:52 UTC, daumayr commented on tests/streams/.gitignore
> +*.txt
It prevents you from accidentally committing files created by tests

2018-01-16 13:32 UTC, smarr commented on tests/streams/.gitignore
> +*.txt
Could you just add this in the top-level .gitignore that already exists? (probably as `tests/streams/*.txt`)

2018-01-16 14:15 UTC, smarr requested changes
Thanks for the update!

There are various little things, any opinion on those?

2018-01-16 14:15 UTC, smarr commented on core-lib/Files.ns
> +      (* We are using this for now since read streams are faster at things like upTo: than input streams *)
Is this your comment, a preexisting one?
Since this is a performance issue, please mark origin (if you, just prefix by `DA:` for instance, and possibly date) so that we know in the future.

2018-01-16 14:15 UTC, smarr commented on core-lib/Files.ns
> +      ^ExternalOutputStream onDescriptor: (self open: #write ifFail: [ :err <ExternalError> | self error: err ])
What's `ExternalError`?
Is this an exception?
If so, perhaps it is better to just signal (i.e. throw it here) instead of using `self error:` which probably quits the VM.

2018-01-16 14:15 UTC, smarr commented on core-lib/Files.ns
> +      (self open: #read ifFail: [ :err <ExternalError> | self error: err ])
same comment as before, and also indentation looks strange.

2018-01-16 14:15 UTC, smarr commented on core-lib/Files.ns
> +      ^ExternalReadWriteStream onDescriptor: (self open: #readwrite ifFail: [ :err <ExternalError> | self error: err ])
Same as above, also for following method.

2018-01-16 14:15 UTC, smarr commented on core-lib/Kernel.ns
> +  public class InvalidArgument signalWith: argument = Exception (
Hm, is the name from Newspeak?
I think, I'd like the class name to be explicit about being an exception.
Possibly named `InvalidArgumentException`, or `ArgumentException` if you are concerned about length?

For the naming, we should try to pick something we'd like to follow as guide, something to follow when it isn't in Newspeak already.
I checked
- Java: IllegalArgumentException
- C#: ArgumentException
- Dart: ArgumentError

any preferences? Perhaps Dart is the most modern one, might be a good source for inspiration?

2018-01-16 14:15 UTC, smarr commented on core-lib/Kernel.ns
> +    InvalidArgument signalWith: message.
We should really build a nice exception thrower in Java, to avoid these unnecessary helpers...

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +	) : (
Most of the methods above are protected, is that intentional? Only few are public interface, if I see it correctly.

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +	(* This class provides the standard implementation of the OutputStream protocol.  It implements all functionality in terms of the message #nextPut:, which subclasses must provide.
I'd like class comments to precede the class normally, I think.
Seems pretty standard in most languages?

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +	| binaryStream <STRM> |) (
STRM?

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +		upTo: del <Object> ^ <Str> = (
Str?

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +		upTo: del <Object> ^ <Str> = (
I think we want a basic name check for type annotations.
To make sure that we at least use things that exist :D

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +			| bytes <Vector[Integer]> s <String> lfs <Integer> j <Integer> delimiter <Character> |
could you add a line break after the types?
This feels hard to read :(

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +) : (
This is unfortunately really to much for me to review.
I don't have a good understanding of what's going on, and what the overall design is :(

2018-01-16 14:15 UTC, smarr commented on core-lib/Streams.ns
> +		onDescriptor: d <DESCRIPTOR> ^ <Instance> = (
DESCRIPTOR?
Instance?
Is this method needed?
Seems to be protected.

2018-01-16 14:15 UTC, smarr commented on core-lib/TestSuite/StreamTests.ns
> +    public testReadBinary2 = (
What's the difference between the two tests?
What is their purpose?
I can't really tell from the method names.
And the assertions aren't self explanatory either.

2018-01-16 14:15 UTC, smarr commented on src/som/vm/constants/KernelObj.java
> +  public static Object signalException(final String selector, final String receiver) {
Hm, I don't like the code duplication with the method above, and the name doesn't isn't really telling me why there are two methods. They do slightly different things, but perhaps the first version is kind of wrong.

Also, would be good to clean up all the duplication around exception throwing. There are quite a number of uses of lookupPrivate, which indicate the same pattern (PathPrims, ArraySetAllStrategy, ...)

2018-01-16 14:16 UTC, smarr commented
For the failing test, the super-instruction candidate tool works like the dym tool. `./tests/superinstructions/test.sh update` should do the trick.

2018-01-16 14:32 UTC, daumayr commented on core-lib/Kernel.ns
> +    InvalidArgument signalWith: message.
yes, would make introduction of new Exceptions easier

2018-01-18 09:34 UTC, daumayr commented on core-lib/Streams.ns
> +	) : (
I removed some dead code and made some more public, the original Newspeak implementation is not well designed in that regard...
Once the Streams are used more (e.g. for the Newspeak parser), we will know what needs to be changed/added.

2018-01-24 16:26 UTC, smarr commented
@daumayr I fixed the incomplete author info on some commits. Hope you don't mind.

And, I'll try to break this up in a couple different PRs. There is just too much going on here for me to make sense of.
First, I'll split out the character stuff.

2018-03-10 14:48 UTC, smarr approved these changes
Ok, let's merge this and improve in place later.
Still don't have a great understanding of how things work, but will probably get polished step by step once merged.

2018-03-10 14:48 UTC, merged